[project]
name = "polypy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "codetiming>=1.4.0",
    "uvloop>=0.22.1",
]

[dependency-groups]
dev = [
    "pyrefly>=0.42.3",
    "ruff>=0.14.6",
]
